### ISSUE TITLE
Add help info when build fails due to permissions issues

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#665]
This is probably the most frequently encountered issue when attempting to install/compile HackerSM64. Something should probably be done about it, though idk what exactly tbh.

**Comment by someone2639** [comment]
What scripts have this issue?

**Comment by gheskett** [comment]
Not really sure, though I think `extract_assets.py` is usually the first one that people end up reporting.

**Comment by gheskett** [comment]
The best way to know for certain would probably be to reproduce it and fix the issues one by one

**Comment by someone2639** [comment]
not sure if i can reproduce this since i dont have a windows install to destroy a downloaded zip with, so i might need a copy of a downloaded+permissions destroyed .zip to fix things as they come up (i could also remove exec perms from everything in the repo but if i mess up i have to redownload and thats annoying lol)

**Comment by gheskett** [comment]
You could try changing all file permissions from `100755` to `100644` and seeing what happens

**Comment by gheskett** [comment]
You might be able to reproduce it by modifying your global git config's `fileMode` setting
